PROJECT: 'rrnet_eth'
VISUALIZE: True
CKPT_DIR: 'checkpoints/'
OUT_DIR: 'outputs'
DEVICE: 'cuda'
METHOD: 'RRNet'
MODEL:
  IMG_SIZE: (256,256)
  BEST_OF_MANY: True
  K: 20
  LATENT_DIST: 'gaussian'
  LATENT_DIM: 32
  ATTENTION: True
  Ra: 0.1
  Randomize: True
  Random_num: 4
  Latent_sample_num_train: 20
  Latent_sample_num_test: 20

  INPUT_LEN: 8
  PRED_LEN: 12 # input and pred_len is defined in 30FPS
  GLOBAL_INPUT_DIM: 6
  DEC_OUTPUT_DIM: 2 
  DROPOUT: 0.5
  
  WITH_FLOW: False
  ENC_CONCAT_TYPE: 'average'
  INPUT_EMBED_SIZE: 256
  FLOW_EMBED_SIZE: 256
  FLOW_HIDDEN_SIZE: 256
  ENC_HIDDEN_SIZE: 256
  DEC_INPUT_SIZE: 256
  DEC_HIDDEN_SIZE: 256
DATASET:
  NAME: 'univ'
  ETH_CONFIG: 'configs/ETH_UCY.json'
  ROOT: 'data/ETH_UCY_trajectron/'
  TRAJECTORY_PATH: 'data/ETH_UCY_trajectron/trajectories/'
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  # TRAIN_MODULE: 'FOL'
  MAX_EPOCH: 50
  BATCH_SIZE: 128
  LR: 0.001
  scheduler: 'exp'
  GAMMA: 0.999
  STAGE1: 15
  STAGE2: 30
  STAGE3: 45
